apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jsonserver
  template:
    metadata:
      labels:
        component: jsonserver
    spec:
      volumes:
        - name: jsonserver-storage
          persistentVolumeClaim:
            claimName: jsonserver-persistent-volume-claim
      containers:
        - name: jsonserver
          image: rabinovich101/jsonserver
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          volumeMounts:
            - name: jsonserver-storage
              mountPath: /data
      volumes:
        - name: jsonserver-storage
          configMap:
            name: jsonserver-storage-config
